GCC   = riscv64-unknown-elf-g++

SBCONFIG=$(SS)/spatial-scheduler/configs/revel-1x1.sbmodel 

DFG_HEADER = $(DFG:.dfg=.dfg.h)

IFLAGS  = -I$(SS_TOOLS)/include               \
	      -I$(SS)/ss-workloads/common/include


$(DFG_HEADER): %.dfg.h: %.dfg
	ss_sched -v -e 114514 $(SBCONFIG) $<

%.out: %.cc $(DFG_HEADER)
	$(GCC) $< $(IFLAGS) -o $@ -O3 -lm

%.s: %.cc $(DFG_HEADER)
	$(GCC) $< $(IFLAGS) -O3 -lm -S -c

clean:
	rm -f *.bc *.ll *.o *.out *.s *.dfg.h
	rm -rf m5out sched viz verif stats
